import random

Quotes = [
    "Ich bin ein Hexer, aber manche nennen mich ... Tim.",
    "Ich furze in eure allgemeine Richtung.",
    "Nur eine kleine Fleischwunde.",
    "Holt hervor, die heilige Handgranate!",
    "Oh bitte, das hier ist eine fröhliche Veranstaltung. Lasst uns jetzt nicht darüber streiten, wer wen getötet hat.",
    "Was haben die Römer uns bisher gutes getan?",
    "Niemand rechnet mit der Spanischen Inquisition!",
    "Aaah, Ja, sinnlose Gewalt. Eines meiner liebsten Werkzeuge.",
    "Ich habe nicht für euch als König gestimmt.",
    "Werft den Purschen zu Poden!",
    "Wartet nur, bis mein Freund Schwanzus Longus davon erfährt!",
    "Ich warne euch, wenn ihr noch ein einziges mal 'Jehova' sagt ....",
    "Life's a piece of shit when you look at it.",
    "Verzeiht, Mylord, der heutige Kreuzzug musste leider abgesagt werden. Der Pöbel hat die Kokosnüsse gestohlen.",
    "I'm not dead.... yet.",
    "Life is a waste of time, and time is a waste of life.",
    "Manchmal kann man alles richtig machen und trotzdem verlieren, das ist das Leben.",
    "Jeder Tag ist ein Kobayashi Maru-Test, und ich bin nicht Kirk.",
    "Jede Schlacht, die nicht geführt werden muss, ist eine gewonnene Schlacht.",
    "Morgen ist auch noch ein Tag.",
    "Hamlet, 4. Akt, Szene 5 Vers 28: 'NEIN!' ",
    "Obwohl das Wahnsinn ist, hat es doch Methode.",
    "Nur der Teufel hat die Macht, eine angenehme Form anzunehmen.",
    "Höre vielen zu, sprich mit wenigen.",
    "Wenn du die Absicht hast, dich zu erneuern, tu es jeden Tag.",
    "Wahre Worte sind nicht immer schön. Schöne Worte sind nicht immer wahr.",
    "Wenn der Wind der Erneuerung weht, bauen die einen Menschen Mauern und die anderen Windmühlen.",
    "Ein starker Geist diskutiert Ideen. \n Ein durschnittlicher Geist diskutiert Ereignisse. \n Ein schwacher Geist diskutiert Leute.",
    "Wer arm an Begierden ist, hat den größten Reichtum.",
    "Wer überall ist, ist nirgendwo wirklich.",
    "Nicht wollen ist der Grund, nicht können nur der Vorwand.",
    "Während man es aufschiebt, geht das Leben vorüber.",
    "Wenn der Clown in die Politik geht, wird nicht der Clown zum Politiker: Der Saal wird zum Zirkus.",
    "Berühmte letzte Worte: 'Mehr Nägel, ich rutsche!' ",
    "Berühmte letzte Worte: 'Alle Speere zu mir!'",
    "Niemand hat die Absicht, eine Mauer zu bauen.",
    "Covfefe!",
    "Was hat es in seinen Taschen, mein Schatz?",
    "Was interessiert mich das Geschwätz von gestern?",
    "Verdammt Jim, er ist tot.",
    "Was machst du denn hier? Hat der Zoo wieder Freigang?",
    "Der Einäugige ist König unter den Blinden.",
    "Mopsgeschwindidschkeit ist im Moment etwas dämlidsch, wir ha'm an Marderschad'n.",
    "Wer in der Vergangenheit verweilt, stirbt jeden Tag ein kleines bisschen mehr.",
    "F.O.C.U.S.: Follow on course until success.",
    "Wenn es deinen Seelenfrieden kostet, ist es zu teuer.",
    "Ich kenne meine Grenzen, ich überschreite sie oft genug.",
    "",
        ]

#print(len(Quotes))
